name:                reddit-telegram-backup
version:             0.1.0.0
github:              "EgorLappo/reddit-telegram-backup"
license:             BSD3
author:              "Egor Lappo"
maintainer:          "egor@ccrma.stanford.edu"
copyright:           "Copyright (c) 2022 Egor Lappo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EgorLappo/reddit-telegram-backup#readme>

dependencies:
- base >= 4.7 && < 5
- text 
- bytestring
- aeson
- time
- http-client-tls
- servant
- servant-client
- polysemy
- polysemy-plugin
- sqlite-simple

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wno-unused-do-bind
- -Wno-unused-top-binds
- -Wredundant-constraints
- -fplugin=Polysemy.Plugin
- -flate-specialise 
- -fspecialise-aggressively

default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - OverloadedStrings
  - DeriveGeneric
  - TemplateHaskell
  - LambdaCase

library:
  source-dirs: src

executables:
  reddit-telegram-backup-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reddit-telegram-backup

tests:
  reddit-telegram-backup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reddit-telegram-backup
